name: Build and Run

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: install coverage tool
      run: |
        sudo apt-get update
        sudo apt-get install -y gcovr

    - name: build_ChargingAdcToAmp
      run: g++ -Wall -Wextra -fprofile-arcs -ftest-coverage -o ChargingAdcToAmp test_ChargingAdcToAmpConverter.cpp ChargingAdcToAmpConverter.c BatteryChargeAnalyser.c
      
    - name: run_ChargingAdcToAmp
      run: ./ChargingAdcToAmp
      
    - name: build_ChargeAndDischargeAdcToAmp
      run: g++ -Wall -Wextra -fprofile-arcs -ftest-coverage -o ChargeAndDischargeAdcToAmp test_ChargingAndDischargingAdcToAmpConverter.cpp WrapperForAbsoluteCurrent.c ChargingAdcToAmpConverter.c BatteryChargeAnalyser.c
      
    - name: run_ChargeAndDischargeAdcToAmp
      run: ./ChargeAndDischargeAdcToAmp

    - name: collect coverage
      run: gcovr --gcov-exclude=".*test.*" -r . --html --html-details -o coverage.html --print-summary

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: ./*.html
        retention-days: 7
